- hosts: localhost
  tasks:
    - name: It's task 1
      ansible.builtin.shell: echo "Шолом мир" >> ~/1.txt
    - name: It's task 2
      ansible.builtin.shell: yum search nasm yasm &>~/2.txt
    - name: It's task 3
      ansible.builtin.yum:
        name: nasm.x86_64
        state: present
    - name: save all facts to host specific file
      copy:
        content: "{{ ansible_delegated_vars[inventory_hostname].vars | to_nice_json }}"
        dest: "{{ playbook_dir }}/{{ ansible_fqdn }}"