- hosts: localhost
  tasks:
  - name: 1
    ansible.builtin.shell: echo "Шолом мир" >> ~/1.txt
  - name: 2
    ansible.builtin.shell: cat > ~/autoinstall.ini << EOF
      EULA_AGREED=Yes
      PRIVACY_POLICY_AGREED=Yes
      USE_KSN=No
      # SERVICE_LOCALE=C
      INSTALL_LICENSE=FRS84-QW7NC-J9Z2W-2CBRP
      UPDATER_SOURCE=KLServers
      # PROXY_SERVER=
      UPDATE_EXECUTE=Yes
      KERNEL_SRCS_INSTALL=Yes
      USE_GUI=Yes
      EOF
