- hosts: localhost
  tasks:
  - name: Install htop
    ansible.builtin.apt: 
     name: htop
  - name: Install acpid
    ansible.builtin.apt: 
     name: acpid
  - name: Install yasm
    ansible.builtin.apt: 
     name: yasm
  - name: Install nasm
    ansible.builtin.apt: 
     name: nasm
  - name: Install sasm
    ansible.builtin.apt: 
     name: sasm
